import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from './styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'

const defaultEndpoint = `https://webservice.recruit.co.jp/hotpepper/gourmet/v1/?key=bdcca1b9768c0479&format=json&large_area=Z011`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();

  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }) {
  console.log(data.results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.results.shop.map((item, index) => {
          return (
            <li key={index}>
               <Link href={item.urls.pc}>
                  <a>
                    <div >
                      <div>
                        <div> {item.name}</div>
                        <div>
                          <div>
                            <span>
                              {item.genre.name}
                            </span>
                            <span>{item.catch}</span>
                          </div>
                          <p> {item.access}</p>
                        </div>
                      </div>
                    </div>
                  </a>
                </Link>
            </li>
          )
        })}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}


